/// Simple two-language string table — no extra package needed.
library;

import 'package:flutter/widgets.dart';
import '../providers/language_provider.dart';
import 'package:provider/provider.dart';

class AppStrings {
  final _Strings _s;
  AppStrings._(this._s);

  static AppStrings of(BuildContext context) {
    final lang = context.watch<LanguageProvider>().language;
    return AppStrings._(lang == 'fr' ? _fr : _en);
  }

  static AppStrings read(BuildContext context) {
    final lang = context.read<LanguageProvider>().language;
    return AppStrings._(lang == 'fr' ? _fr : _en);
  }

  // ── Auth ──────────────────────────────────────────────────────────────────
  String get appName         => _s.appName;
  String get appTagline      => _s.appTagline;
  String get email           => _s.email;
  String get password        => _s.password;
  String get confirmPassword => _s.confirmPassword;
  String get fullName        => _s.fullName;
  String get login           => _s.login;
  String get logout          => _s.logout;
  String get register        => _s.register;
  String get noAccount       => _s.noAccount;
  String get hasAccount      => _s.hasAccount;
  String get loginError      => _s.loginError;

  // ── Navigation ────────────────────────────────────────────────────────────
  String get dashboard  => _s.dashboard;
  String get devices    => _s.devices;
  String get sites      => _s.sites;
  String get users      => _s.users;
  String get profile    => _s.profile;
  String get settings   => _s.settings;
  String get history    => _s.history;
  String get logs       => _s.logs;
  String get calibration => _s.calibration;

  // ── Sites ─────────────────────────────────────────────────────────────────
  String get newSite    => _s.newSite;
  String get siteName   => _s.siteName;
  String get siteAddress => _s.siteAddress;
  String get createSite => _s.createSite;
  String get editSite   => _s.editSite;
  String get deleteSite => _s.deleteSite;
  String get noSites    => _s.noSites;
  String get allDevices => _s.allDevices;

  // ── Devices ───────────────────────────────────────────────────────────────
  String get newDevice    => _s.newDevice;
  String get deviceId     => _s.deviceId;
  String get deviceName   => _s.deviceName;
  String get addDevice    => _s.addDevice;
  String get editDevice   => _s.editDevice;
  String get deleteDevice => _s.deleteDevice;
  String get noDevices    => _s.noDevices;
  String get scanQr       => _s.scanQr;
  String get orManual     => _s.orManual;
  String get assignSite   => _s.assignSite;
  String get control      => _s.control;
  String get online       => _s.online;
  String get offline      => _s.offline;
  String get unstable     => _s.unstable;
  String get unknown      => _s.unknown;

  // ── Fuel & tank ───────────────────────────────────────────────────────────
  String get fuelLevel       => _s.fuelLevel;
  String get fuelVolume      => _s.fuelVolume;
  String get temperature     => _s.temperature;
  String get batteryLevel    => _s.batteryLevel;
  String get signalStrength  => _s.signalStrength;
  String get fuelCritical    => _s.fuelCritical;
  String get fuelLow         => _s.fuelLow;
  String get fuelNormal      => _s.fuelNormal;
  String get fuelFull        => _s.fuelFull;
  String get alertThreshold  => _s.alertThreshold;
  String get monitorDevice   => _s.monitorDevice;
  String get lastSeen        => _s.lastSeen;

  // ── Tank config ───────────────────────────────────────────────────────────
  String get tankConfig             => _s.tankConfig;
  String get tankShape              => _s.tankShape;
  String get cylindricalVertical    => _s.cylindricalVertical;
  String get cylindricalHorizontal  => _s.cylindricalHorizontal;
  String get rectangular            => _s.rectangular;
  String get heightCm               => _s.heightCm;
  String get diameterCm             => _s.diameterCm;
  String get lengthCm               => _s.lengthCm;
  String get widthCm                => _s.widthCm;
  String get sensorOffsetCm         => _s.sensorOffsetCm;
  String get alertThresholdPct      => _s.alertThresholdPct;
  String get sendConfig             => _s.sendConfig;
  String get configSent             => _s.configSent;
  String get tankConfigHint         => _s.tankConfigHint;

  // ── Users ─────────────────────────────────────────────────────────────────
  String get newUser    => _s.newUser;
  String get role       => _s.role;
  String get active     => _s.active;
  String get suspended  => _s.suspended;
  String get suspend    => _s.suspend;
  String get restore    => _s.restore;
  String get deleteUser => _s.deleteUser;
  String get noUsers    => _s.noUsers;
  String get technician => _s.technician;
  String get user       => _s.user;
  String get admin      => _s.admin;

  // ── Profile ───────────────────────────────────────────────────────────────
  String get language       => _s.language;
  String get french         => _s.french;
  String get english        => _s.english;
  String get changePassword => _s.changePassword;
  String get version        => _s.version;

  // ── Common ────────────────────────────────────────────────────────────────
  String get save        => _s.save;
  String get cancel      => _s.cancel;
  String get delete      => _s.delete;
  String get confirm     => _s.confirm;
  String get edit        => _s.edit;
  String get add         => _s.add;
  String get search      => _s.search;
  String get refresh     => _s.refresh;
  String get loading     => _s.loading;
  String get error       => _s.error;
  String get success     => _s.success;
  String get required    => _s.required;
  String get optional    => _s.optional;
  String get allFields   => _s.allFields;
  String get noData      => _s.noData;
  String get areYouSure  => _s.areYouSure;
  String get cannotUndo  => _s.cannotUndo;
  String get techPanel   => _s.techPanel;
  String get hello       => _s.hello;
  String get myDevices   => _s.myDevices;
  String get techLogs    => _s.techLogs;
}

// ── Internal string tables ────────────────────────────────────────────────────

class _Strings {
  const _Strings();
  String get appName              => '';
  String get appTagline           => '';
  String get email                => '';
  String get password             => '';
  String get confirmPassword      => '';
  String get fullName             => '';
  String get login                => '';
  String get logout               => '';
  String get register             => '';
  String get noAccount            => '';
  String get hasAccount           => '';
  String get loginError           => '';
  String get dashboard            => '';
  String get devices              => '';
  String get sites                => '';
  String get users                => '';
  String get profile              => '';
  String get settings             => '';
  String get history              => '';
  String get logs                 => '';
  String get calibration          => '';
  String get newSite              => '';
  String get siteName             => '';
  String get siteAddress          => '';
  String get createSite           => '';
  String get editSite             => '';
  String get deleteSite           => '';
  String get noSites              => '';
  String get allDevices           => '';
  String get newDevice            => '';
  String get deviceId             => '';
  String get deviceName           => '';
  String get addDevice            => '';
  String get editDevice           => '';
  String get deleteDevice         => '';
  String get noDevices            => '';
  String get scanQr               => '';
  String get orManual             => '';
  String get assignSite           => '';
  String get control              => '';
  String get online               => '';
  String get offline              => '';
  String get unstable             => '';
  String get unknown              => '';
  String get fuelLevel            => '';
  String get fuelVolume           => '';
  String get temperature          => '';
  String get batteryLevel         => '';
  String get signalStrength       => '';
  String get fuelCritical         => '';
  String get fuelLow              => '';
  String get fuelNormal           => '';
  String get fuelFull             => '';
  String get alertThreshold       => '';
  String get monitorDevice        => '';
  String get lastSeen             => '';
  String get tankConfig           => '';
  String get tankShape            => '';
  String get cylindricalVertical  => '';
  String get cylindricalHorizontal => '';
  String get rectangular          => '';
  String get heightCm             => '';
  String get diameterCm           => '';
  String get lengthCm             => '';
  String get widthCm              => '';
  String get sensorOffsetCm       => '';
  String get alertThresholdPct    => '';
  String get sendConfig           => '';
  String get configSent           => '';
  String get tankConfigHint       => '';
  String get newUser              => '';
  String get role                 => '';
  String get active               => '';
  String get suspended            => '';
  String get suspend              => '';
  String get restore              => '';
  String get deleteUser           => '';
  String get noUsers              => '';
  String get technician           => '';
  String get user                 => '';
  String get admin                => '';
  String get language             => '';
  String get french               => '';
  String get english              => '';
  String get changePassword       => '';
  String get version              => '';
  String get save                 => '';
  String get cancel               => '';
  String get delete               => '';
  String get confirm              => '';
  String get edit                 => '';
  String get add                  => '';
  String get search               => '';
  String get refresh              => '';
  String get loading              => '';
  String get error                => '';
  String get success              => '';
  String get required             => '';
  String get optional             => '';
  String get allFields            => '';
  String get noData               => '';
  String get areYouSure           => '';
  String get cannotUndo           => '';
  String get techPanel            => '';
  String get hello                => '';
  String get myDevices            => '';
  String get techLogs             => '';
}

class _En extends _Strings {
  const _En();
  @override String get appName              => 'FuelSense';
  @override String get appTagline           => 'Smart fuel level monitoring';
  @override String get email               => 'Email address';
  @override String get password            => 'Password';
  @override String get confirmPassword     => 'Confirm password';
  @override String get fullName            => 'Full name';
  @override String get login              => 'Sign In';
  @override String get logout             => 'Sign Out';
  @override String get register           => 'Create Account';
  @override String get noAccount          => "Don't have an account? Register";
  @override String get hasAccount         => 'Already have an account? Sign in';
  @override String get loginError         => 'Invalid email or password';
  @override String get dashboard          => 'Dashboard';
  @override String get devices            => 'Devices';
  @override String get sites              => 'Sites';
  @override String get users              => 'Users';
  @override String get profile            => 'Profile';
  @override String get settings           => 'Settings';
  @override String get history            => 'History';
  @override String get logs               => 'Logs';
  @override String get calibration        => 'Calibration';
  @override String get newSite            => 'New Site';
  @override String get siteName           => 'Site name';
  @override String get siteAddress        => 'Address (optional)';
  @override String get createSite         => 'Create Site';
  @override String get editSite           => 'Edit Site';
  @override String get deleteSite         => 'Delete Site';
  @override String get noSites            => 'No sites yet. Tap + to add one.';
  @override String get allDevices         => 'All Sensors';
  @override String get newDevice          => 'New Sensor';
  @override String get deviceId           => 'Device ID';
  @override String get deviceName         => 'Sensor name (optional)';
  @override String get addDevice          => 'Add Sensor';
  @override String get editDevice         => 'Edit Sensor';
  @override String get deleteDevice       => 'Delete Sensor';
  @override String get noDevices          => 'No fuel sensors in this site.';
  @override String get scanQr             => 'Scan QR Code';
  @override String get orManual           => 'or enter manually';
  @override String get assignSite         => 'Assign to site';
  @override String get control            => 'Monitor';
  @override String get online             => 'Online';
  @override String get offline            => 'Offline';
  @override String get unstable           => 'Unstable';
  @override String get unknown            => 'Unknown';
  @override String get fuelLevel          => 'Fuel Level';
  @override String get fuelVolume         => 'Volume';
  @override String get temperature        => 'Temperature';
  @override String get batteryLevel       => 'Battery';
  @override String get signalStrength     => 'Signal';
  @override String get fuelCritical       => 'Critical';
  @override String get fuelLow           => 'Low';
  @override String get fuelNormal         => 'Normal';
  @override String get fuelFull           => 'Full';
  @override String get alertThreshold     => 'Alert Threshold';
  @override String get monitorDevice      => 'View Details';
  @override String get lastSeen           => 'Last seen';
  @override String get tankConfig         => 'Tank Configuration';
  @override String get tankShape          => 'Tank Shape';
  @override String get cylindricalVertical  => 'Cylindrical (Vertical)';
  @override String get cylindricalHorizontal => 'Cylindrical (Horizontal)';
  @override String get rectangular        => 'Rectangular';
  @override String get heightCm           => 'Height (cm)';
  @override String get diameterCm         => 'Diameter (cm)';
  @override String get lengthCm           => 'Length (cm)';
  @override String get widthCm            => 'Width (cm)';
  @override String get sensorOffsetCm     => 'Sensor Offset (cm)';
  @override String get alertThresholdPct  => 'Alert Threshold (%)';
  @override String get sendConfig         => 'Send Config to Device';
  @override String get configSent         => 'Configuration sent to device';
  @override String get tankConfigHint     => 'These dimensions allow the device to calculate the exact fuel volume from the sensor reading.';
  @override String get newUser            => 'New User';
  @override String get role               => 'Role';
  @override String get active             => 'Active';
  @override String get suspended          => 'Suspended';
  @override String get suspend            => 'Suspend';
  @override String get restore            => 'Restore';
  @override String get deleteUser         => 'Delete User';
  @override String get noUsers            => 'No users yet.';
  @override String get technician         => 'Technician';
  @override String get user               => 'User';
  @override String get admin              => 'Admin';
  @override String get language           => 'Language';
  @override String get french             => 'Français';
  @override String get english            => 'English';
  @override String get changePassword     => 'Change Password';
  @override String get version            => 'Version';
  @override String get save               => 'Save';
  @override String get cancel             => 'Cancel';
  @override String get delete             => 'Delete';
  @override String get confirm            => 'Confirm';
  @override String get edit               => 'Edit';
  @override String get add                => 'Add';
  @override String get search             => 'Search';
  @override String get refresh            => 'Refresh';
  @override String get loading            => 'Loading…';
  @override String get error              => 'Error';
  @override String get success            => 'Success';
  @override String get required           => 'Required';
  @override String get optional           => 'Optional';
  @override String get allFields          => 'All fields are required';
  @override String get noData             => 'No data available';
  @override String get areYouSure         => 'Are you sure?';
  @override String get cannotUndo         => 'This action cannot be undone.';
  @override String get techPanel          => 'Tech Panel';
  @override String get hello              => 'Hello';
  @override String get myDevices          => 'My Sensors';
  @override String get techLogs           => 'Tech Logs';
}

class _Fr extends _Strings {
  const _Fr();
  @override String get appName              => 'FuelSense';
  @override String get appTagline           => 'Surveillance intelligente du carburant';
  @override String get email               => 'Adresse e-mail';
  @override String get password            => 'Mot de passe';
  @override String get confirmPassword     => 'Confirmer le mot de passe';
  @override String get fullName            => 'Nom complet';
  @override String get login              => 'Se connecter';
  @override String get logout             => 'Se déconnecter';
  @override String get register           => 'Créer un compte';
  @override String get noAccount          => 'Pas de compte ? S\'inscrire';
  @override String get hasAccount         => 'Déjà un compte ? Se connecter';
  @override String get loginError         => 'Email ou mot de passe invalide';
  @override String get dashboard          => 'Tableau de bord';
  @override String get devices            => 'Capteurs';
  @override String get sites              => 'Sites';
  @override String get users              => 'Utilisateurs';
  @override String get profile            => 'Profil';
  @override String get settings           => 'Paramètres';
  @override String get history            => 'Historique';
  @override String get logs               => 'Journaux';
  @override String get calibration        => 'Calibration';
  @override String get newSite            => 'Nouveau site';
  @override String get siteName           => 'Nom du site';
  @override String get siteAddress        => 'Adresse (facultatif)';
  @override String get createSite         => 'Créer le site';
  @override String get editSite           => 'Modifier le site';
  @override String get deleteSite         => 'Supprimer le site';
  @override String get noSites            => 'Aucun site. Appuyez sur + pour en ajouter.';
  @override String get allDevices         => 'Tous les capteurs';
  @override String get newDevice          => 'Nouveau capteur';
  @override String get deviceId           => 'ID capteur';
  @override String get deviceName         => 'Nom du capteur (facultatif)';
  @override String get addDevice          => 'Ajouter le capteur';
  @override String get editDevice         => 'Modifier le capteur';
  @override String get deleteDevice       => 'Supprimer le capteur';
  @override String get noDevices          => 'Aucun capteur dans ce site.';
  @override String get scanQr             => 'Scanner le QR Code';
  @override String get orManual           => 'ou saisir manuellement';
  @override String get assignSite         => 'Affecter au site';
  @override String get control            => 'Surveiller';
  @override String get online             => 'En ligne';
  @override String get offline            => 'Hors ligne';
  @override String get unstable           => 'Instable';
  @override String get unknown            => 'Inconnu';
  @override String get fuelLevel          => 'Niveau carburant';
  @override String get fuelVolume         => 'Volume';
  @override String get temperature        => 'Température';
  @override String get batteryLevel       => 'Batterie';
  @override String get signalStrength     => 'Signal';
  @override String get fuelCritical       => 'Critique';
  @override String get fuelLow           => 'Bas';
  @override String get fuelNormal         => 'Normal';
  @override String get fuelFull           => 'Plein';
  @override String get alertThreshold     => 'Seuil d\'alerte';
  @override String get monitorDevice      => 'Voir les détails';
  @override String get lastSeen           => 'Vu le';
  @override String get tankConfig         => 'Configuration du réservoir';
  @override String get tankShape          => 'Forme du réservoir';
  @override String get cylindricalVertical  => 'Cylindrique (vertical)';
  @override String get cylindricalHorizontal => 'Cylindrique (horizontal)';
  @override String get rectangular        => 'Rectangulaire';
  @override String get heightCm           => 'Hauteur (cm)';
  @override String get diameterCm         => 'Diamètre (cm)';
  @override String get lengthCm           => 'Longueur (cm)';
  @override String get widthCm            => 'Largeur (cm)';
  @override String get sensorOffsetCm     => 'Décalage capteur (cm)';
  @override String get alertThresholdPct  => 'Seuil d\'alerte (%)';
  @override String get sendConfig         => 'Envoyer la config au capteur';
  @override String get configSent         => 'Configuration envoyée au capteur';
  @override String get tankConfigHint     => 'Ces dimensions permettent au capteur de calculer le volume exact à partir de la mesure brute.';
  @override String get newUser            => 'Nouvel utilisateur';
  @override String get role               => 'Rôle';
  @override String get active             => 'Actif';
  @override String get suspended          => 'Suspendu';
  @override String get suspend            => 'Suspendre';
  @override String get restore            => 'Restaurer';
  @override String get deleteUser         => 'Supprimer l\'utilisateur';
  @override String get noUsers            => 'Aucun utilisateur.';
  @override String get technician         => 'Technicien';
  @override String get user               => 'Utilisateur';
  @override String get admin              => 'Administrateur';
  @override String get language           => 'Langue';
  @override String get french             => 'Français';
  @override String get english            => 'English';
  @override String get changePassword     => 'Changer le mot de passe';
  @override String get version            => 'Version';
  @override String get save               => 'Enregistrer';
  @override String get cancel             => 'Annuler';
  @override String get delete             => 'Supprimer';
  @override String get confirm            => 'Confirmer';
  @override String get edit               => 'Modifier';
  @override String get add                => 'Ajouter';
  @override String get search             => 'Rechercher';
  @override String get refresh            => 'Actualiser';
  @override String get loading            => 'Chargement…';
  @override String get error              => 'Erreur';
  @override String get success            => 'Succès';
  @override String get required           => 'Obligatoire';
  @override String get optional           => 'Facultatif';
  @override String get allFields          => 'Tous les champs sont obligatoires';
  @override String get noData             => 'Aucune donnée disponible';
  @override String get areYouSure         => 'Êtes-vous sûr ?';
  @override String get cannotUndo         => 'Cette action est irréversible.';
  @override String get techPanel          => 'Panneau technique';
  @override String get hello              => 'Bonjour';
  @override String get myDevices          => 'Mes capteurs';
  @override String get techLogs           => 'Journaux tech';
}

const _en = _En();
const _fr = _Fr();
